ENV_PATH = ".env.private"

# TODO These names could become classes or tuples and be tidier
SYNOLOGY_IP_NAME = "SYNOLOGY_IP"
SYNOLOGY_PORT_NAME = "SYNOLOGY_PORT"
SYNOLOGY_USERNAME_NAME = "SYNOLOGY_USERNAME"
SYNOLOGY_PASSWORD_NAME = "SYNOLOGY_PASSWORD"

DELUGE_USERNAME_NAME = "DELUGE_USERNAME"
DELUGE_PASSWORD_NAME = "DELUGE_PASSWORD"
DELUGE_IP_NAME = "DELUGE_IP"
DELUGE_PORT_NAME = "DELUGE_PORT"


PRIVATE_SSH_KEY_PATH_NAME = "PRIVATE_SSH_KEY_PATH"
