
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
before_install:
  - docker-compose build tests
script:
  - docker-compose run --rm tests docker/scripts/tests