version: '3.7'
services:
  build:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/build
    container_name: build
    volumes:
      - .:/app:delegated
    environment:
      USER: ${USER:-}
  deploy:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/deploy
    container_name: deploy
    volumes:
      - .:/app:delegated
    environment:
      USER: ${USER:-}
  install:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/install
    container_name: install
    volumes:
      - .:/app:delegated
  tests:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/tests
    container_name: tests
    volumes:
      - .:/app:delegated
    environment:
      # General
      PYTHONUNBUFFERED: 'true'
      PYTHONPATH: '/app/synology-toolset:/app/tests:'
      ENVIRONMENT_NAME: 'test'
    env_file:
      - .env.sample