version: "3.7"
services:
  build:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/build
    container_name: build
    volumes:
      - .:/app:delegated
  deploy:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/deploy
    container_name: deploy
    volumes:
      - .:/app:delegated
  install:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/install
    container_name: install
    volumes:
      - .:/app:delegated
      - ~/.ssh:/root/.ssh
    env_file:
      - $HOME/.synotools/credentials
  tests:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/tests
    container_name: tests
    volumes:
      - .:/app:delegated
    environment:
      # General
      PYTHONUNBUFFERED: "true"
      PYTHONPATH: "/app/synotools:/app/tests:"
      ENVIRONMENT_NAME: "test"
    env_file:
      - .env.tests

  integration-tests:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/scripts/integration-tests
    container_name: integration-tests
    volumes:
      - .:/app:delegated
    environment:
      # General
      PYTHONUNBUFFERED: "true"
      PYTHONPATH: "/app/synotools:/app/tests:"
      ENVIRONMENT_NAME: "test"

