agent_queue: &agent_queue 'queue=medium'

steps:
  - label: ':hammer: Build'
    command: |
      ./build.docker
    agents:
      - *agent_queue
    artifact_paths:
      - "artifacts/*"

  - wait

  - label: ':hammer: Unit Tests'
    command: |
      ./tests.docker
    agents:
      - *agent_queue
    artifact_paths:
      - "artifacts/*"

  # - label: ':hammer: Flake8'
  #   command: |
  #     ./flake8.docker
  #   agents:
  #     - *agent_queue
  #   artifact_paths:
  #     - "artifacts/*"

  - label: ':black_heart: Black Formatted'
    branches: '!master'
    command: |
      black . --check --diff
    agents:
      - *agent_queue
