#!/bin/bash

set -o pipefail
set -u

mkdir artifacts || true

echo "--> Cleaning out cached pyc files..."
find . -name "*.pyc" -delete

echo "--> Running integration tests..."

$(which pytest) -v --durations=20 --tb=short tests/integration
