#!/bin/bash

set -o pipefail
set -u

echo "--> Running shell scripts test..."

# Try to use system installed bats, if it does not work try the dependencies one
bats tests/scripts/ || dependencies/bats/bin/bats tests/scripts/
