#!/bin/bash

set -o pipefail
set -u

mkdir artifacts || true

echo "--> Cleaning out cached pyc files..."
find . -name "*.pyc" -delete

echo "--> Running tests with coverage..."

coverage run \
    --source=synotools \
    -- $(which pytest) -v --durations=20 --tb=short --junit-xml=artifacts/test-report.xml tests/unit

echo "--> Coverage stats..."
coverage html

echo "--> Coverage report..."
coverage report

COVERAGE_REPORT_EXIT_CODE=$?

if [[ COVERAGE_REPORT_EXIT_CODE -gt 0 ]]; then
    echo >&2 "Coverage exit code: $COVERAGE_REPORT_EXIT_CODE"
else
    echo "Coverage exit code: $COVERAGE_REPORT_EXIT_CODE"
fi

COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
