#!/bin/bash

set -o pipefail
set -u

mkdir artifacts || true

# Give explicit permission for bats to run
chmod +x /usr/local/bin/bats || true
dependencies/bats/bin/bats || true

# Give explicit permission for all .bats scripts

# Run tests normally
/bin/bash ./docker/scripts/tests

# Run coveralls in addition to it
COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
