ENV_PATH = ".env.private"
SYNOLOGY_IP_NAME = "SYNOLOGY_IP"
SYNOLOGY_PORT_NAME = "SYNOLOGY_PORT"
SYNOLOGY_USERNAME_NAME = "SYNOLOGY_USERNAME"
SYNOLOGY_PASSWORD_NAME = "SYNOLOGY_PASSWORD"

DELUGE_USERNAME_NAME = "DELUGE_USERNAME"
DELUGE_PASSWORD_NAME = "DELUGE_PASSWORD"

PRIVATE_SSH_KEY_PATH_NAME = "PRIVATE_SSH_KEY_PATH"
